version: "3"
services:

  rpc:
    image: ethereum/client-go
    entrypoint: /root/init-script.sh
    command:
      - "--datadir=/datadir/geth"
      - "--networkid=7"
      - "--config=/datadir/config.toml"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
      - "--syncmode=full"
      - "--rpc.allow-unprotected-txs"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/geth:/datadir/geth"
      - "./init-script.sh:/root/init-script.sh"
      - "./config.toml:/datadir/config.toml"
    ports:
      - 30305:30303
      - 8545:8545
      - 8546:8546
    restart: always

